trigger:
- main

pool:
  name: 'Default'   # Use your local agent pool name
steps:
# Step 1: Build with Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'   # Set memory allocation for Maven build
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'    # Set JDK version (adjust if needed)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true   # Publish JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Location of test results
    goals: 'package'            # Use 'package' to build your project