# azure-pipelines.yml
trigger:
  branches:
    include:
      - master # Specify the branch to trigger the build

pool:
  name: 'mylocalpool' # Your custom Azure VM agent pool

steps:
# 1. Checkout the code using the Git command (as 'Checkout@2' is not available)
- script: |
    git clone https://github.com/EASWAR17/spring.git
    cd YOUR_REPO
  displayName: 'Checkout code from GitHub'

# 2. Set up JDK manually (since 'UseJava' is not available, assume JDK is pre-installed)
# If JDK isn't installed on your VM, you need to manually install it using:
# sudo apt install openjdk-11-jdk -y

# 3. Run Maven build (assuming Maven is pre-installed on your VM)
- script: |
    mvn -version
    mvn clean package
  displayName: 'Build with Maven'

# 4. Publish the JAR artifact to the pipeline's artifact store (optional)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)/target/*.jar'  # Adjust to your actual target directory
    artifactName: 'drop'
    publishLocation: 'Container'
